name: Claude Bug AutoFix

on:
  # Listen for @claude mentions in issues
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  handle-bug:
    # Only run if @claude is mentioned or it's a workflow_dispatch event
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.comment.body, '@claude') ||
      contains(github.event.issue.body, '@claude')
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
    
    steps:
      - name: Use Claude to Fix Bug
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: specify allowed tools
          allowed_tools: "Bash(npm:*),Bash(git:*),View,Edit,Replace,GlobTool,GrepTool"
          # Optional: add custom instructions
