name: Claude Bug AutoFix

on:
  # Add manual trigger for testing
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Bug description or prompt for Claude'
        required: true
        type: string

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rjwalters/claude-code-action@feature/manual-trigger-support
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
